version: '3'

services:
  mynctl:
    image: makesoftware/casper-nctl:latest
    container_name: mynctl
    ports:
      - 11101-11105:11101-11105
      - 14101-14105:14101-14105
      - 18101-18105:18101-18105
      - 25101-25105:25101-25105
    environment:
      PREDEFINED_ACCOUNTS: 'true'
      #PATH_TO_CONFIG_TOML: '/home/casper/config/config.toml'
      #PATH_TO_CHAINSPEC: '/home/casper/config/chainspec.toml'
      #MINIMUM_ROUND_EXPONENT: '12'
      #MAXIMUM_ROUND_EXPONENT: '14'
      DEPLOY_DELAY: '5sec'

  cors-anywhere:
    container_name: cors-anywhere
    profiles: ["cors-anywhere"]
    build:
      context: ./cors
      dockerfile: cors-anywhere.Dockerfile
    tty: true
    environment:
      PORT: 11100
    ports:
      - 11100:11100
